#!/bin/bash
echo "================================================"
echo "  Google OAuth Configuration URLs"
echo "================================================"
echo ""
echo "📋 Copy these URLs to configure Google OAuth:"
echo ""
echo "1️⃣  SUPABASE SITE URL:"
echo "   https://$REPLIT_DEV_DOMAIN"
echo ""
echo "2️⃣  SUPABASE REDIRECT URLs (add all):"
echo "   https://$REPLIT_DEV_DOMAIN/auth/callback"
echo "   https://$REPLIT_DEV_DOMAIN/**"
echo "   http://localhost:3000/auth/callback"
echo "   http://localhost:3000/**"
echo ""
echo "3️⃣  GOOGLE CLOUD CONSOLE - Authorized Redirect URIs:"
echo "   https://$REPLIT_DEV_DOMAIN/auth/callback"
echo "   https://<your-supabase-project-id>.supabase.co/auth/v1/callback"
echo "   http://localhost:3000/auth/callback"
echo ""
echo "================================================"
echo "📖 See GOOGLE_OAUTH_SETUP.md for detailed instructions"
echo "================================================"
