import { MigrationInterface, QueryRunner } from "typeorm";

export class CreateUserRolesTable1756957347033 implements MigrationInterface {
    name = 'CreateUserRolesTable1756957347033'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "sessions" DROP CONSTRAINT "sessions_user_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "invitations" DROP CONSTRAINT "invitations_client_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "invitations" DROP CONSTRAINT "invitations_created_by_fkey"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP CONSTRAINT "audit_logs_actor_user_id_fkey"`);
        await queryRunner.query(`DROP INDEX "public"."idx_users_email"`);
        await queryRunner.query(`DROP INDEX "public"."idx_sessions_user_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_sessions_token_family"`);
        await queryRunner.query(`DROP INDEX "public"."idx_sessions_expires_at"`);
        await queryRunner.query(`DROP INDEX "public"."idx_invitations_email"`);
        await queryRunner.query(`DROP INDEX "public"."idx_invitations_token"`);
        await queryRunner.query(`DROP INDEX "public"."idx_invitations_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_audit_logs_actor"`);
        await queryRunner.query(`DROP INDEX "public"."idx_audit_logs_entity"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "chk_users_status"`);
        await queryRunner.query(`CREATE TABLE "documents" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "eor_profile_id" uuid NOT NULL, "document_type" "public"."documents_document_type_enum" NOT NULL, "file_name" character varying NOT NULL, "file_path" character varying NOT NULL, "content_type" character varying NOT NULL, "file_size" integer NOT NULL, "sha256_checksum" character varying NOT NULL, "version_id" character varying NOT NULL, "is_current" boolean NOT NULL DEFAULT false, "uploaded_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_ac51aa5181ee2036f5ca482857c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "eor_profiles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "date_of_birth" date, "phone_number" character varying, "address_line1" character varying, "address_line2" character varying, "city" character varying, "state_province" character varying, "postal_code" character varying, "job_title" character varying, "department" character varying, "employee_id" character varying, "start_date" date, "employment_type" character varying, "manager_name" character varying, "skills" jsonb, "experience_years" integer, "education" jsonb, "certifications" jsonb, "languages" jsonb, "profile_completion_percentage" integer NOT NULL DEFAULT '0', "is_profile_complete" boolean NOT NULL DEFAULT false, "profile_status" character varying NOT NULL DEFAULT 'incomplete', "country_code" character varying(2) NOT NULL, "timezone" character varying, "emergency_contact_name" character varying, "emergency_contact_phone" character varying, "emergency_contact_relationship" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_301360aa19c0c64c37507b2d76d" UNIQUE ("user_id"), CONSTRAINT "REL_301360aa19c0c64c37507b2d76" UNIQUE ("user_id"), CONSTRAINT "PK_133431267b1b7b82edc93a036a8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "employment_records" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "client_id" uuid NOT NULL, "start_date" date NOT NULL, "end_date" date, "role" character varying(100) NOT NULL, "status" character varying(20) NOT NULL DEFAULT 'active', "migrated_from_zoho" boolean NOT NULL DEFAULT false, "zoho_employment_id" character varying(100), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "unique_active_employment_per_client" UNIQUE ("user_id", "client_id", "status"), CONSTRAINT "CHK_898282bcae1e0ae6bd69f21dc4" CHECK ("end_date" IS NULL OR "end_date" >= "start_date"), CONSTRAINT "CHK_e437a1064f23726ca4522f35a0" CHECK ("status" IN ('active', 'inactive', 'terminated', 'completed')), CONSTRAINT "PK_12524bc9c212bc229148563915c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_a98d305bd9c09a4ee7da7a8eb3" ON "employment_records" ("start_date") `);
        await queryRunner.query(`CREATE INDEX "IDX_633369691ec3f202f45cebb5a3" ON "employment_records" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_44647ac5c8f293e89f11b3dba9" ON "employment_records" ("client_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_478ac6932654d54eac2f82a5ab" ON "employment_records" ("user_id") `);
        await queryRunner.query(`CREATE TABLE "salary_history" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "employment_record_id" uuid NOT NULL, "salary_amount" numeric(12,2) NOT NULL, "salary_currency" character varying(3) NOT NULL DEFAULT 'USD', "effective_date" date NOT NULL, "change_reason" character varying(100) NOT NULL, "changed_by" uuid, "migrated_from_zoho" boolean NOT NULL DEFAULT false, "zoho_salary_id" character varying(100), "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "unique_effective_date_per_employment" UNIQUE ("employment_record_id", "effective_date"), CONSTRAINT "CHK_7217c53ed308ce85044ca23455" CHECK ("salary_amount" > 0), CONSTRAINT "PK_796fc91fc02d8e1b35a08c3de32" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_e95a5187bae79f6c823045a337" ON "salary_history" ("effective_date") `);
        await queryRunner.query(`CREATE INDEX "IDX_5c56fe595714603a8f31f593ed" ON "salary_history" ("employment_record_id") `);
        await queryRunner.query(`CREATE TABLE "user_roles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "role_type" character varying(50) NOT NULL, "scope" character varying(20) NOT NULL, "scope_entity_id" uuid, "granted_by" uuid, "expires_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "CHK_21696d74f91e511e83cd077942" CHECK ("scope" IN ('user', 'group', 'client', 'all')), CONSTRAINT "CHK_b430253d58e98fc265b9c767fe" CHECK ("role_type" IN ('candidate', 'eor', 'admin', 'timesheet_approver', 'leave_approver')), CONSTRAINT "PK_8acd5cf26ebd158416f477de799" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_32cbb6f005afc7507c7864e8b4" ON "user_roles" ("expires_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_ded0b49981fd798786012c0f4f" ON "user_roles" ("scope") `);
        await queryRunner.query(`CREATE INDEX "IDX_7d15b7e3fb6d4d19748adce2ed" ON "user_roles" ("role_type") `);
        await queryRunner.query(`CREATE INDEX "IDX_87b8888186ca9769c960e92687" ON "user_roles" ("user_id") `);
        await queryRunner.query(`ALTER TABLE "clients" ADD "contact_info" jsonb`);
        await queryRunner.query(`ALTER TABLE "clients" ADD "status" character varying(20) NOT NULL DEFAULT 'active'`);
        await queryRunner.query(`ALTER TABLE "clients" ADD "migrated_from_zoho" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "clients" ADD "zoho_client_id" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "invitations" ADD "accepted_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "invitations" ADD "accepted_by" uuid`);
        await queryRunner.query(`ALTER TABLE "invitations" ADD "deleted_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "users_email_key"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "email" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email")`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "password_hash"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "password_hash" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "status" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "is_active" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "email_verified" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "email_verification_token"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "email_verification_token" character varying`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "password_reset_token"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "password_reset_token" character varying`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "migrated_from_zoho" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "sessions" DROP COLUMN "refresh_token_hash"`);
        await queryRunner.query(`ALTER TABLE "sessions" ADD "refresh_token_hash" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "sessions" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "sessions" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "sessions" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "sessions" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "clients" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "clients" ADD "name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "clients" ADD CONSTRAINT "UQ_99e921caf21faa2aab020476e44" UNIQUE ("name")`);
        await queryRunner.query(`ALTER TABLE "clients" DROP COLUMN "description"`);
        await queryRunner.query(`ALTER TABLE "clients" ADD "description" character varying`);
        await queryRunner.query(`ALTER TABLE "clients" ALTER COLUMN "is_active" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "clients" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "clients" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "clients" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "clients" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "invitations" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "invitations" ADD "email" character varying NOT NULL`);
        await queryRunner.query(`ALTER TYPE "public"."invitations_country_enum" RENAME TO "invitations_country_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."invitations_country_enum" AS ENUM('IN', 'LK', 'PH')`);
        await queryRunner.query(`ALTER TABLE "invitations" ALTER COLUMN "country" TYPE "public"."invitations_country_enum" USING "country"::"text"::"public"."invitations_country_enum"`);
        await queryRunner.query(`DROP TYPE "public"."invitations_country_enum_old"`);
        await queryRunner.query(`ALTER TYPE "public"."invitations_role_enum" RENAME TO "invitations_role_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."invitations_role_enum" AS ENUM('EOR', 'Admin')`);
        await queryRunner.query(`ALTER TABLE "invitations" ALTER COLUMN "role" TYPE "public"."invitations_role_enum" USING "role"::"text"::"public"."invitations_role_enum"`);
        await queryRunner.query(`DROP TYPE "public"."invitations_role_enum_old"`);
        await queryRunner.query(`ALTER TABLE "invitations" ALTER COLUMN "client_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "invitations" DROP CONSTRAINT "invitations_token_key"`);
        await queryRunner.query(`ALTER TABLE "invitations" DROP COLUMN "token"`);
        await queryRunner.query(`ALTER TABLE "invitations" ADD "token" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "invitations" ADD CONSTRAINT "UQ_e577dcf9bb6d084373ed3998509" UNIQUE ("token")`);
        await queryRunner.query(`ALTER TABLE "invitations" ALTER COLUMN "status" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "invitations" ALTER COLUMN "created_by" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "invitations" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "invitations" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "invitations" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "invitations" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP CONSTRAINT "audit_logs_pkey"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD CONSTRAINT "PK_1bb179d048bbc581caa3b013439" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "at"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ALTER COLUMN "actor_user_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "actor_role"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "actor_role" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "action"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "action" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "entity_type"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "entity_type" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ALTER COLUMN "entity_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "ip"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "ip" character varying`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "user_agent"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "user_agent" character varying`);
        await queryRunner.query(`CREATE INDEX "IDX_97672ac88f789774dd47f7c8be" ON "users" ("email") `);
        await queryRunner.query(`CREATE INDEX "IDX_9cfe37d28c3b229a350e086d94" ON "sessions" ("expires_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_6cb6e543d1f7a7af2d0bb5246d" ON "sessions" ("token_family") `);
        await queryRunner.query(`CREATE INDEX "IDX_085d540d9f418cfbdc7bd55bb1" ON "sessions" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_e577dcf9bb6d084373ed399850" ON "invitations" ("token") `);
        await queryRunner.query(`CREATE INDEX "IDX_97ab59cb592c7cec109741b592" ON "invitations" ("email") `);
        await queryRunner.query(`CREATE INDEX "IDX_f160d97a931844109de9d04228" ON "audit_logs" ("actor_user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_7421efc125d95e413657efa3c6" ON "audit_logs" ("entity_type", "entity_id") `);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "CHK_ac185881bfade295dd02abb641" CHECK ("status" IN ('active', 'inactive', 'archived'))`);
        await queryRunner.query(`ALTER TABLE "clients" ADD CONSTRAINT "CHK_c30a5ccec578c3004aeaa11ba0" CHECK ("status" IN ('active', 'inactive'))`);
        await queryRunner.query(`ALTER TABLE "sessions" ADD CONSTRAINT "FK_085d540d9f418cfbdc7bd55bb19" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invitations" ADD CONSTRAINT "FK_b3ca92622941bab607e687b3e3a" FOREIGN KEY ("client_id") REFERENCES "clients"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invitations" ADD CONSTRAINT "FK_2afdbc73ee1fe16cf1f3929e920" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invitations" ADD CONSTRAINT "FK_fdcaac54a139fa30a51ce246f98" FOREIGN KEY ("accepted_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD CONSTRAINT "FK_f160d97a931844109de9d04228f" FOREIGN KEY ("actor_user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "documents" ADD CONSTRAINT "FK_f60594d7e54adefa0b8854919cb" FOREIGN KEY ("eor_profile_id") REFERENCES "eor_profiles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "eor_profiles" ADD CONSTRAINT "FK_301360aa19c0c64c37507b2d76d" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employment_records" ADD CONSTRAINT "FK_478ac6932654d54eac2f82a5ab9" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employment_records" ADD CONSTRAINT "FK_44647ac5c8f293e89f11b3dba98" FOREIGN KEY ("client_id") REFERENCES "clients"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "salary_history" ADD CONSTRAINT "FK_5c56fe595714603a8f31f593edb" FOREIGN KEY ("employment_record_id") REFERENCES "employment_records"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "salary_history" ADD CONSTRAINT "FK_6fbd146356f8db3ff47212f0fb1" FOREIGN KEY ("changed_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_roles" ADD CONSTRAINT "FK_87b8888186ca9769c960e926870" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_roles" ADD CONSTRAINT "FK_5d2beedacbe986e0dbabba67a84" FOREIGN KEY ("granted_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "user_roles" DROP CONSTRAINT "FK_5d2beedacbe986e0dbabba67a84"`);
        await queryRunner.query(`ALTER TABLE "user_roles" DROP CONSTRAINT "FK_87b8888186ca9769c960e926870"`);
        await queryRunner.query(`ALTER TABLE "salary_history" DROP CONSTRAINT "FK_6fbd146356f8db3ff47212f0fb1"`);
        await queryRunner.query(`ALTER TABLE "salary_history" DROP CONSTRAINT "FK_5c56fe595714603a8f31f593edb"`);
        await queryRunner.query(`ALTER TABLE "employment_records" DROP CONSTRAINT "FK_44647ac5c8f293e89f11b3dba98"`);
        await queryRunner.query(`ALTER TABLE "employment_records" DROP CONSTRAINT "FK_478ac6932654d54eac2f82a5ab9"`);
        await queryRunner.query(`ALTER TABLE "eor_profiles" DROP CONSTRAINT "FK_301360aa19c0c64c37507b2d76d"`);
        await queryRunner.query(`ALTER TABLE "documents" DROP CONSTRAINT "FK_f60594d7e54adefa0b8854919cb"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP CONSTRAINT "FK_f160d97a931844109de9d04228f"`);
        await queryRunner.query(`ALTER TABLE "invitations" DROP CONSTRAINT "FK_fdcaac54a139fa30a51ce246f98"`);
        await queryRunner.query(`ALTER TABLE "invitations" DROP CONSTRAINT "FK_2afdbc73ee1fe16cf1f3929e920"`);
        await queryRunner.query(`ALTER TABLE "invitations" DROP CONSTRAINT "FK_b3ca92622941bab607e687b3e3a"`);
        await queryRunner.query(`ALTER TABLE "sessions" DROP CONSTRAINT "FK_085d540d9f418cfbdc7bd55bb19"`);
        await queryRunner.query(`ALTER TABLE "clients" DROP CONSTRAINT "CHK_c30a5ccec578c3004aeaa11ba0"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "CHK_ac185881bfade295dd02abb641"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7421efc125d95e413657efa3c6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f160d97a931844109de9d04228"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_97ab59cb592c7cec109741b592"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e577dcf9bb6d084373ed399850"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_085d540d9f418cfbdc7bd55bb1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6cb6e543d1f7a7af2d0bb5246d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9cfe37d28c3b229a350e086d94"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_97672ac88f789774dd47f7c8be"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "user_agent"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "user_agent" text`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "ip"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "ip" inet`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ALTER COLUMN "entity_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "entity_type"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "entity_type" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "action"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "action" character varying(100) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "actor_role"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "actor_role" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ALTER COLUMN "actor_user_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "at"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "at" TIMESTAMP WITH TIME ZONE DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP CONSTRAINT "PK_1bb179d048bbc581caa3b013439"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD CONSTRAINT "audit_logs_pkey" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "invitations" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "invitations" ADD "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "invitations" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "invitations" ADD "created_at" TIMESTAMP WITH TIME ZONE DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "invitations" ALTER COLUMN "created_by" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "invitations" ALTER COLUMN "status" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "invitations" DROP CONSTRAINT "UQ_e577dcf9bb6d084373ed3998509"`);
        await queryRunner.query(`ALTER TABLE "invitations" DROP COLUMN "token"`);
        await queryRunner.query(`ALTER TABLE "invitations" ADD "token" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "invitations" ADD CONSTRAINT "invitations_token_key" UNIQUE ("token")`);
        await queryRunner.query(`ALTER TABLE "invitations" ALTER COLUMN "client_id" DROP NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."invitations_role_enum_old" AS ENUM('EOR', 'EMPLOYEE', 'CONTRACTOR', 'ADMIN')`);
        await queryRunner.query(`ALTER TABLE "invitations" ALTER COLUMN "role" TYPE "public"."invitations_role_enum_old" USING "role"::"text"::"public"."invitations_role_enum_old"`);
        await queryRunner.query(`DROP TYPE "public"."invitations_role_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."invitations_role_enum_old" RENAME TO "invitations_role_enum"`);
        await queryRunner.query(`CREATE TYPE "public"."invitations_country_enum_old" AS ENUM('US', 'CA', 'UK', 'DE', 'FR', 'IN', 'AU', 'JP', 'BR', 'MX')`);
        await queryRunner.query(`ALTER TABLE "invitations" ALTER COLUMN "country" TYPE "public"."invitations_country_enum_old" USING "country"::"text"::"public"."invitations_country_enum_old"`);
        await queryRunner.query(`DROP TYPE "public"."invitations_country_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."invitations_country_enum_old" RENAME TO "invitations_country_enum"`);
        await queryRunner.query(`ALTER TABLE "invitations" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "invitations" ADD "email" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "clients" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "clients" ADD "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "clients" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "clients" ADD "created_at" TIMESTAMP WITH TIME ZONE DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "clients" ALTER COLUMN "is_active" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "clients" DROP COLUMN "description"`);
        await queryRunner.query(`ALTER TABLE "clients" ADD "description" text`);
        await queryRunner.query(`ALTER TABLE "clients" DROP CONSTRAINT "UQ_99e921caf21faa2aab020476e44"`);
        await queryRunner.query(`ALTER TABLE "clients" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "clients" ADD "name" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "sessions" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "sessions" ADD "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "sessions" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "sessions" ADD "created_at" TIMESTAMP WITH TIME ZONE DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "sessions" DROP COLUMN "refresh_token_hash"`);
        await queryRunner.query(`ALTER TABLE "sessions" ADD "refresh_token_hash" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "created_at" TIMESTAMP WITH TIME ZONE DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "migrated_from_zoho" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "password_reset_token"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "password_reset_token" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "email_verification_token"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "email_verification_token" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "email_verified" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "is_active" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "status" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "password_hash"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "password_hash" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "email" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "users_email_key" UNIQUE ("email")`);
        await queryRunner.query(`ALTER TABLE "invitations" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "invitations" DROP COLUMN "accepted_by"`);
        await queryRunner.query(`ALTER TABLE "invitations" DROP COLUMN "accepted_at"`);
        await queryRunner.query(`ALTER TABLE "clients" DROP COLUMN "zoho_client_id"`);
        await queryRunner.query(`ALTER TABLE "clients" DROP COLUMN "migrated_from_zoho"`);
        await queryRunner.query(`ALTER TABLE "clients" DROP COLUMN "status"`);
        await queryRunner.query(`ALTER TABLE "clients" DROP COLUMN "contact_info"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_87b8888186ca9769c960e92687"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7d15b7e3fb6d4d19748adce2ed"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ded0b49981fd798786012c0f4f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_32cbb6f005afc7507c7864e8b4"`);
        await queryRunner.query(`DROP TABLE "user_roles"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5c56fe595714603a8f31f593ed"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e95a5187bae79f6c823045a337"`);
        await queryRunner.query(`DROP TABLE "salary_history"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_478ac6932654d54eac2f82a5ab"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_44647ac5c8f293e89f11b3dba9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_633369691ec3f202f45cebb5a3"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a98d305bd9c09a4ee7da7a8eb3"`);
        await queryRunner.query(`DROP TABLE "employment_records"`);
        await queryRunner.query(`DROP TABLE "eor_profiles"`);
        await queryRunner.query(`DROP TABLE "documents"`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "chk_users_status" CHECK (((status)::text = ANY ((ARRAY['active'::character varying, 'inactive'::character varying, 'archived'::character varying])::text[])))`);
        await queryRunner.query(`CREATE INDEX "idx_audit_logs_entity" ON "audit_logs" ("entity_type", "entity_id") `);
        await queryRunner.query(`CREATE INDEX "idx_audit_logs_actor" ON "audit_logs" ("actor_user_id") `);
        await queryRunner.query(`CREATE INDEX "idx_invitations_status" ON "invitations" ("status") `);
        await queryRunner.query(`CREATE INDEX "idx_invitations_token" ON "invitations" ("token") `);
        await queryRunner.query(`CREATE INDEX "idx_invitations_email" ON "invitations" ("email") `);
        await queryRunner.query(`CREATE INDEX "idx_sessions_expires_at" ON "sessions" ("expires_at") `);
        await queryRunner.query(`CREATE INDEX "idx_sessions_token_family" ON "sessions" ("token_family") `);
        await queryRunner.query(`CREATE INDEX "idx_sessions_user_id" ON "sessions" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "idx_users_email" ON "users" ("email") `);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD CONSTRAINT "audit_logs_actor_user_id_fkey" FOREIGN KEY ("actor_user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invitations" ADD CONSTRAINT "invitations_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invitations" ADD CONSTRAINT "invitations_client_id_fkey" FOREIGN KEY ("client_id") REFERENCES "clients"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sessions" ADD CONSTRAINT "sessions_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

}
